"""empty message

Revision ID: 270150c399d1
Revises: ca611aedfb67
Create Date: 2020-04-07 17:17:53.503900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '270150c399d1'
down_revision = 'ca611aedfb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('Venue', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
