"""empty message

Revision ID: ceed2c30f9f4
Revises: 270150c399d1
Create Date: 2020-04-10 21:39:04.962192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceed2c30f9f4'
down_revision = '270150c399d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('date_added', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('date_added', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'date_added')
    op.drop_column('Artist', 'date_added')
    # ### end Alembic commands ###
